[tools]
hugo = "latest"

[tasks.dev]
run = """
hugo server --buildDrafts
"""

[tasks.initPaperMod]
run = """
mkdir -p themes
git submodule update --init --recursive
"""

[tasks.updatePaperMod]
run = "git submodule update --remote --merge"
